/*
 * main.h
 *
 *  Created on: Aug 14, 2023
 *      Author: mpcukur
 */

#ifndef MAIN_H_
#define MAIN_H_

typedef enum {
    en_KeyExpansion,
    en_SubBytes,
    en_ShiftRows,
    en_xtime,
    en_MixColumns,
    en_AddRoundKey,
    en_Cipher,
    en_InvShiftRows,
    en_InvSubBytes,
    en_InvMixColumns,
    en_InvCipher,
    en_fors_sk_to_leaf,
    en_message_to_indices,
    en_fors_gen_sk,
    en_fors_gen_leaf,
    en_load_bigendian_64,
    en_load_bigendian_32,
    en_store_bigendian_32,
    en_crypto_hashblocks_sha256,
    en_store_bigendian_64,
    en_wots_gen_leaf,
    en_base_w,
    en_wots_gen_sk,
    en_gen_chain,
    en_wots_checksum,
    en_chain_lengths,
    en_seed_state,
    en_set_layer_addr,
    en_set_keypair_addr,
    en_wots_sign,
    en_sha256_inc_finalize,
    en_setDebugLevel,
    en_getTime_ms,
    en_AES_ECB_decrypt,
    en_memmove,
    en_crypto_sign_seed_keypair,
    en_set_tree_index,
    en_sha256_inc_blocks,
    en_crypto_sign_secretkeybytes,
    en_u32_to_bytes,
    en_memcpy,
    en_AES256_CTR_DRBG_Update,
    en_thash,
    en_sendUartByteWaitTransmitDone,
    en_ull_to_bytes,
    en_seedexpander,
    en_wots_gen_pk,
    en_crypto_sign_bytes,
    en_read32BitDataFromAddress,
    en_mgf1,
    en_crypto_sign_publickeybytes,
    en_copy_subtree_addr,
    en_AES_ECB_encrypt,
    en_initialize_hash_function,
    en_resetTimeStamp,
    en_randombytes,
    en_wots_pk_from_sig,
    en_set_hash_addr,
    en_sha256_inc_init,
    en_crypto_sign_keypair,
    en_randombytes_init,
    en_crypto_sign_signature,
    en_seedexpander_init,
    en_write32BitDataToAddress,
    en_compute_root,
    en_set_chain_addr,
    en_dbg_printf,
    en_getU64FromTwoU32s,
    en_crypto_sign,
    en_fors_sign,
    en_gen_message_random,
    en_crypto_sign_verify,
    en_memcmp,
    en_getTimeDiff_ms,
    en_benchmark,
    en_set_tree_height,
    en_memset,
    en_main,
    en_AES256_ECB,
    en_prf_addr,
    en_set_type,
    en_crypto_sign_seedbytes,
    en_hash_message,
    en_copy_keypair_addr,
    en_sha256,
    en_getCpuCycleLow,
    en_crypto_sign_open,
    en_AES_init_ctx,
    en_set_tree_addr,
    en_bytes_to_ull,
    en_strlen,
    en_intToString,
    en_write8BitDataToAddress,
    en_treehash,
    en_fors_pk_from_sig,
    en_getTimeStamp,
    en_getCpuCycleHigh,
    en_intToHexString,
    NUM_FUNCTIONS // Always keep this at the end
} FunctionEnum;

#endif /* MAIN_H_ */
